name: hpp
channels:
  - conda-forge
dependencies:
  - python>3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - dask
  - dask-jobqueue
  - distributed
  - joblib
  - scalene
  - cupy
  - cuda-version<=12.8
  - jupyter
  - jupyterlab
